// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOCspKZo3KRJf4zONcQUYM4RNElenkEfs',
    appId: '1:478631523017:web:8d7b41945d21c4521f9318',
    messagingSenderId: '478631523017',
    projectId: 'contactsapp-37bba',
    authDomain: 'contactsapp-37bba.firebaseapp.com',
    storageBucket: 'contactsapp-37bba.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtJla7HlMASCnxJTr1NkfL2d7a2HbloFo',
    appId: '1:478631523017:android:2571f6d1359994fc1f9318',
    messagingSenderId: '478631523017',
    projectId: 'contactsapp-37bba',
    storageBucket: 'contactsapp-37bba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6B_sNl2EEf-j5yF3NSGKh0mvb_A2P7yo',
    appId: '1:478631523017:ios:77aa22e31c2b75431f9318',
    messagingSenderId: '478631523017',
    projectId: 'contactsapp-37bba',
    storageBucket: 'contactsapp-37bba.appspot.com',
    iosBundleId: 'com.example.contatsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6B_sNl2EEf-j5yF3NSGKh0mvb_A2P7yo',
    appId: '1:478631523017:ios:09659ec4b549a2be1f9318',
    messagingSenderId: '478631523017',
    projectId: 'contactsapp-37bba',
    storageBucket: 'contactsapp-37bba.appspot.com',
    iosBundleId: 'com.example.contatsApp.RunnerTests',
  );
}
